topics: # topics published out of this machine to receivers specified above
 - name: "control_manager/mpc_tracker/predicted_trajectory"
   compress: false # enable bz2 compression
   rate: 2.0
 - name: "control_manager/trajectory_original/poses"
   compress: false # enable bz2 compression
   rate: 1.0
 - name: "control_manager/mpc_tracker/predicted_trajectory_debugging"
   compress: false # enable bz2 compression
   rate: 1.0
 - name: "control_manager/mpc_tracker/diagnostics"
   compress: false # enable bz2 compression
   rate: 1.0
 - name: "control_manager/diagnostics"
   compress: false # enable bz2 compression
   rate: 1.0
 - name: "odometry/slow_odom"
   compress: false # enable bz2 compression
   rate: 1.0

services:
  - name: "/*/control_manager/goto_trajectory_start"
    type: std_srvs/Trigger
  - name: "/*/control_manager/start_trajectory_tracking"
    type: std_srvs/Trigger
  - name: "/*/control_manager/trajectory_reference"
    type: mrs_msgs/TrajectoryReferenceSrv
